
package com.donlim.aps.webservice.scm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DONLIM_SCM_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_SCM_QUERYSYNC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DONLIMSCMQUERYSYNC {


    /**
     *
     * @param svcHdr
     * @return
     *     returns com.donlim.aps.webservice.scm.SvcHdrsTypes
     */
    @WebMethod(operationName = "DONLIM_SCM_QUERYSYNC", action = "http://www.example.org/DONLIM_SCM_QUERYSYNC/DONLIM_SCM_QUERYSYNC")
    @WebResult(name = "SvcHdrs", targetNamespace = "")
    @RequestWrapper(localName = "DONLIM_SCM_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_SCM_QUERYSYNC/", className = "com.donlim.aps.webservice.scm.DONLIMSCMQUERYSYNC_Type")
    @ResponseWrapper(localName = "DONLIM_SCM_QUERYSYNCResponse", targetNamespace = "http://www.example.org/DONLIM_SCM_QUERYSYNC/", className = "com.donlim.aps.webservice.scm.DONLIMSCMQUERYSYNCResponse")
    public SvcHdrsTypes donlimSCMQUERYSYNC(
        @WebParam(name = "SvcHdr", targetNamespace = "")
                SvcHdrType svcHdr);

}
