
package com.donlim.aps.webservice.scm;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DONLIM_SCM_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_SCM_QUERYSYNC/", wsdlLocation = "http://10.233.0.138:7801/WS/DONLIM/SCM/DONLIM_SCM_QUERYSYNC?wsdl")
public class DONLIMSCMQUERYSYNC_Service
    extends Service
{

    private final static URL DONLIMSCMQUERYSYNC_WSDL_LOCATION;
    private final static WebServiceException DONLIMSCMQUERYSYNC_EXCEPTION;
    private final static QName DONLIMSCMQUERYSYNC_QNAME = new QName("http://www.example.org/DONLIM_SCM_QUERYSYNC/", "DONLIM_SCM_QUERYSYNC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.233.0.138:7801/WS/DONLIM/SCM/DONLIM_SCM_QUERYSYNC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DONLIMSCMQUERYSYNC_WSDL_LOCATION = url;
        DONLIMSCMQUERYSYNC_EXCEPTION = e;
    }

    public DONLIMSCMQUERYSYNC_Service() {
        super(__getWsdlLocation(), DONLIMSCMQUERYSYNC_QNAME);
    }

    public DONLIMSCMQUERYSYNC_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DONLIMSCMQUERYSYNC_QNAME, features);
    }

    public DONLIMSCMQUERYSYNC_Service(URL wsdlLocation) {
        super(wsdlLocation, DONLIMSCMQUERYSYNC_QNAME);
    }

    public DONLIMSCMQUERYSYNC_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DONLIMSCMQUERYSYNC_QNAME, features);
    }

    public DONLIMSCMQUERYSYNC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DONLIMSCMQUERYSYNC_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DONLIMSCMQUERYSYNC
     */
    @WebEndpoint(name = "DONLIM_SCM_QUERYSYNCSOAP")
    public DONLIMSCMQUERYSYNC getDONLIMSCMQUERYSYNCSOAP() {
        return super.getPort(new QName("http://www.example.org/DONLIM_SCM_QUERYSYNC/", "DONLIM_SCM_QUERYSYNCSOAP"), DONLIMSCMQUERYSYNC.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DONLIMSCMQUERYSYNC
     */
    @WebEndpoint(name = "DONLIM_SCM_QUERYSYNCSOAP")
    public DONLIMSCMQUERYSYNC getDONLIMSCMQUERYSYNCSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DONLIM_SCM_QUERYSYNC/", "DONLIM_SCM_QUERYSYNCSOAP"), DONLIMSCMQUERYSYNC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DONLIMSCMQUERYSYNC_EXCEPTION!= null) {
            throw DONLIMSCMQUERYSYNC_EXCEPTION;
        }
        return DONLIMSCMQUERYSYNC_WSDL_LOCATION;
    }

}
