
package com.donlim.aps.webservice.mcas;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DONLIM_MCAS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_MCAS_QUERYSYNC/", wsdlLocation = "http://10.233.0.138:7801/WS/DONLIM/ESB/DONLIM_MCAS2_QUERYSYNC?wsdl")
public class DONLIMMCASQUERYSYNC_Service
    extends Service
{

    private final static URL DONLIMMCASQUERYSYNC_WSDL_LOCATION;
    private final static WebServiceException DONLIMMCASQUERYSYNC_EXCEPTION;
    private final static QName DONLIMMCASQUERYSYNC_QNAME = new QName("http://www.example.org/DONLIM_MCAS_QUERYSYNC/", "DONLIM_MCAS_QUERYSYNC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.233.0.138:7801/WS/DONLIM/ESB/DONLIM_MCAS2_QUERYSYNC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DONLIMMCASQUERYSYNC_WSDL_LOCATION = url;
        DONLIMMCASQUERYSYNC_EXCEPTION = e;
    }

    public DONLIMMCASQUERYSYNC_Service() {
        super(__getWsdlLocation(), DONLIMMCASQUERYSYNC_QNAME);
    }

    public DONLIMMCASQUERYSYNC_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DONLIMMCASQUERYSYNC_QNAME, features);
    }

    public DONLIMMCASQUERYSYNC_Service(URL wsdlLocation) {
        super(wsdlLocation, DONLIMMCASQUERYSYNC_QNAME);
    }

    public DONLIMMCASQUERYSYNC_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DONLIMMCASQUERYSYNC_QNAME, features);
    }

    public DONLIMMCASQUERYSYNC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DONLIMMCASQUERYSYNC_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DONLIMMCASQUERYSYNC
     */
    @WebEndpoint(name = "DONLIM_MCAS_QUERYSYNCSOAP")
    public DONLIMMCASQUERYSYNC getDONLIMMCASQUERYSYNCSOAP() {
        return super.getPort(new QName("http://www.example.org/DONLIM_MCAS_QUERYSYNC/", "DONLIM_MCAS_QUERYSYNCSOAP"), DONLIMMCASQUERYSYNC.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DONLIMMCASQUERYSYNC
     */
    @WebEndpoint(name = "DONLIM_MCAS_QUERYSYNCSOAP")
    public DONLIMMCASQUERYSYNC getDONLIMMCASQUERYSYNCSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DONLIM_MCAS_QUERYSYNC/", "DONLIM_MCAS_QUERYSYNCSOAP"), DONLIMMCASQUERYSYNC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DONLIMMCASQUERYSYNC_EXCEPTION!= null) {
            throw DONLIMMCASQUERYSYNC_EXCEPTION;
        }
        return DONLIMMCASQUERYSYNC_WSDL_LOCATION;
    }

}
