
package com.donlim.aps.webservice.mcas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DONLIM_MCAS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_MCAS_QUERYSYNC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DONLIMMCASQUERYSYNC {


    /**
     *
     * @param svcHdrs
     * @param user01
     * @param svcHdr
     */
    @WebMethod(operationName = "DONLIM_MCAS_QUERYSYNC", action = "http://www.example.org/DONLIM_MCAS_QUERYSYNC/DONLIM_MCAS_QUERYSYNC")
    @RequestWrapper(localName = "DONLIM_MCAS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_MCAS_QUERYSYNC/", className = "com.donlim.aps.webservice.mcas.DONLIMMCASQUERYSYNC_Type")
    @ResponseWrapper(localName = "DONLIM_MCAS_QUERYSYNCResponse", targetNamespace = "http://www.example.org/DONLIM_MCAS_QUERYSYNC/", className = "com.donlim.aps.webservice.mcas.DONLIMMCASQUERYSYNCResponse")
    public void donlimMCASQUERYSYNC(
        @WebParam(name = "SvcHdr", targetNamespace = "")
                SvcHdrType svcHdr,
        @WebParam(name = "User01", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> user01,
        @WebParam(name = "SvcHdrs", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<SvcHdrsTypes> svcHdrs);

}
