
package com.donlim.aps.webservice.aps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DONLIM_APS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_APS_QUERYSYNC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DONLIMAPSQUERYSYNC {


    /**
     *
     * @param svcHdr
     * @return
     *     returns io.renren.service.aps.SvcHdrsType
     */
    @WebMethod(operationName = "DONLIM_APS_QUERYSYNC", action = "http://www.example.org/DONLIM_APS_QUERYSYNC/DONLIM_APS_QUERYSYNC")
    @WebResult(name = "SvcHdrs", targetNamespace = "")
    @RequestWrapper(localName = "DONLIM_APS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_APS_QUERYSYNC/", className = "com.donlim.aps.webservice.aps.DONLIMAPSQUERYSYNC_Type")
    @ResponseWrapper(localName = "DONLIM_APS_QUERYSYNCResponse", targetNamespace = "http://www.example.org/DONLIM_APS_QUERYSYNC/", className = "com.donlim.aps.webservice.aps.DONLIMAPSQUERYSYNCResponse")
    public SvcHdrsType donlimAPSQUERYSYNC(
        @WebParam(name = "SvcHdr", targetNamespace = "")
        SvcHdrType svcHdr);

}
